const express = require('express');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const { spawn } = require('child_process');
const fs = require('fs-extra');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

const app = express();
const PORT = process.env.PORT || 3000;

// ========== কুকি ফাইল তৈরি করা (আপনার দেওয়া কন্টেন্ট) ==========
const COOKIE_CONTENT = `# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.sonyliv.com	TRUE	/	FALSE	1814957313	WZRK_G	e8d3f8ff9575448a8aadea86cda96be3
.sonyliv.com	TRUE	/	FALSE	1814957313	_ga	GA1.1.313898065.1779369999
.sonyliv.com	TRUE	/	FALSE	1788173313	_fbp	fb.1.1779370000062.459480759852758265
.sonyliv.com	TRUE	/	FALSE	1814957314	afUserId	2d8129aa-3972-44f0-a13a-90beceacf380-p
.sonyliv.com	TRUE	/	FALSE	1787145998	_gcl_au	1.1.1029985000.1779369998.395921699.1779370022.1779370021
.sonyliv.com	TRUE	/	TRUE	1811933273	_abck	6A366DE1CDE5213D8874AE65DC04B925~-1~YAAQckU5F/XalUieAQAAY3HyhxD01O2SYjDffQoe0X/HVpu+1EvW99mu4yOORHAglp0X1OW047Yz7LAmucnhHyWSFSXZBagcxyO+ZpCBVJsCabE3I/r04fBRhFoQXsc8YLksH056PDgV0x4r2RvNDZKTDwcn0ouo8dFqH2hsnreqi3cgAQ+v4R1BtYzoqSYYTTDtwpIuuXgasTWCueeP0IfT9y1kDuxZtF0yqnejtY1/V1zzyEQ8oCrB9TslylFBjRQxy6uVzzTvPwvEJ4xE5zaOVE7Xeh0i8NXZCjXrmV/6wMjIY58Z2y9GfgWZQRtfrL6pFOeolPaX+j/v2lb0pTr0xvqpD8CrdfFAsV9QwQ8HTIPBylv2s/9odYG3q3pVHGJmNeDyidCzqFz3fawCLQV4ou87dPHFsNsLaYDPjNzqcetiOhfr4ywpzeD3/UVz7HoSKxzDI1H3GyPtMaFf6FlhWxXfoaHz~-1~-1~-1~-1~-1
.sonyliv.com	TRUE	/	FALSE	1780412380	ak_bmsc	589CBBBA4D792508A18A2A951CB7A2F8~000000000000000000000000000000~YAAQlEU5F5Sag0ieAQAA0RF/iABbnecekJXrVXtgOQWiYa0PMfDP63wrKupsfL70FyXw3uR7WvQRX7P2/dUwjiLSgMJRPeALR50dbXm0gRSL2AyYIJUwasTMD6hXLd/8xsvEuwbgrHSa0S+Zy0wtpW1RiNm4xgBgjI+47Th4R97btJqUpjfO8w5hJgZVgRa0bp4KvT4TsALjMi2Iq0xgpF2VDj+M7oCr5FLsgqGiTeGzyzO01cSDAObWYnUUAPoEb1w0FwSUItsmduH6+UGKo3CnPCm9QejbGc4j1ckptqhuWfc6tsSQsg61V829y6o8gYDI+YH0gwhEauRdz5oVehdQISC5mq7/ym2PnMoPwP6t5txMbe4rbnLV5Bexjy11zd4BinbEaoOsRcbmVhjY82U=
.sonyliv.com	TRUE	/	FALSE	1780411673	bm_sz	BD3807B48E3E8296DC751C33AD1C7C9C~YAAQPVI2F0BckEmeAQAANKmAiAD66gosDyoUY7TVy1x08bPvAZERLMnhEaEP/tvFPLkpX7dANtd5TEd20ZlZlEC1LrpgqhbXSx45NCBuW0x8J7s9p0E+bDRMXOniHVHA0VESIb9ZgfNo1V7IXKfsztFlYHeaYjlLtXXIAE6rCArAjkA/1SlDf30r8mol0iW5Zdb7G1YpHlZFZcT9RekxTSRM8yzL4GPDI3vvKedW9mV0lWLAtynu2/Wywvy+TE/lxgg66coLWG+aUNr3mLeSGk/jcjEfIOo7Yp09pmnsGbJ7LfIJmQ2kRk+hle0Znup7rP25k58rTJdgYqju5ouhPIZZIfrR0H/DQrjIriUPS9woqPEIJIYYe1RGJd1KlGM7Cu6nOmCBswIWC82VS9XebsySkfowX0GwDxuwU3uamOCg47NVRR+f6W/fOAs4IuJy9RUBZfxONZ0uUdehRUTfaR1L/GfQPnNEoMmMfByKN9C8wPhPyf/f+o94udLxkqxNfy+nVoOBPSt4EN82ySXZzbEJSkE=~3225666~3420721
.sonyliv.com	TRUE	/	FALSE	1781002074	AF_SYNC	1780397274915
.sonyliv.com	TRUE	/	TRUE	1780397491	ak_cf	utm3-ie2y-33ya-tbzv
.sonyliv.com	TRUE	/	TRUE	1780412381	bm_sv	93D9C703575B7AC1EF5D61A9E71DE370~YAAQPVI2Fz9ckEmeAQAANKmAiACdaX6PhVPbICrl8KrBpW9NYMf71EwewhgPONab0ogmqlR3bC7duTm0KfCNuX2uszlPRT+qVWFDwvmUZqC9VXlo8k5cV6TW+K49Z1laYzNmhQL0SfkcB9tMhxB5j2fCs9kgTnPE5Einxr1AeOoKyxB13cVJxxP5+wX9P7/IA0BtYxul3nFFIyObll+3s4EWZqmWlAHtbjE1b649vwtVfYB4sebJzZT0++8eCNZPLFg=~1
.sonyliv.com	TRUE	/	FALSE	1780398515	WZRK_S_48K-8WW-754Z	%7B%22p%22%3A2%2C%22s%22%3A1780397273%2C%22t%22%3A1780397315%7D
.sonyliv.com	TRUE	/	FALSE	1814957316	_ga_1WZE8VR8Q1	GS2.1.s1780397273$o2$g1$t1780397316$j17$l0$h0
.sonyliv.com	TRUE	/	TRUE	0	CloudFront-Key-Pair-Id	APKAI7J6JOJ4USP3NLWQ
.sonyliv.com	TRUE	/	TRUE	0	CloudFront-Policy	eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGl2Mi5zb255bGl2LmNvbS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzgwNDQ5Nzg4fX19XX0_
.sonyliv.com	TRUE	/	TRUE	0	CloudFront-Signature	GSVdSk6IQd13TWY1-7iTlDDR8~a6d39RS9ImHEtYOC~rWEGk03AI0ghvuCrff3sCoIO4VSygJ5dP6Eb6xbf9FjvJJ7RIosukudBZ6fwA62DGmA4uxDCEAXhUbVVMM40Dq2gbyFkfJFrqTrFul3TG~Z--Fv6yVdEV0TgI6ZYCOcAxNJIlO56aUjU1Fy-a4t5ERbXFTKQ6rDjkoTr6y6V9u7SmJb-NxO0u79VFlWWrXVg8r3SA~c~q2zL8gm02KXYPxIT90tyqldzXMRbLsJ9zABU9-6W2eh5E01NKqGURiqbplZ02txWpq51jdObD-8iw2JGNBiit4O~5aFtLJIwCw85WXboi261wk4RUqghWRs6mKd84ORRRj8DhS01Me3zXY0ImMNWlclgw6sKSLmqwZXBYPYq8j1bvAOSoecToyhY-dGQnJZlIer3GAHZK2Nepel0gDJumqW4BaP-IK-ws-V0aScOIcrKudB~LxBCWfJKfexGxrDyzEnhS6s~6WOZoOClW3zoPmge3dEy32CJB6BQyPAfUdIGJi5T8z1WJUt-bkzbIY6J8opyjSYsgZvqoIg85cPMYBLaO5BomUrN0clQU7hjmSyvyZQWX6YHX4LStCNdiDai-apbCZ2mUyQo1~tvtarGEQT-Dinl-Yfq61joMPhBC6-xVnmem1efqYIA_
www.sonyliv.com	FALSE	/	TRUE	1810906016	sl_device_token	35f6581490be40e29b48724a9950d62f-1779370014044
www.sonyliv.com	FALSE	/	TRUE	1810906016	sl_ppid	35f6581490be40e29b48724a9950d62f
apiv2.sonyliv.com	FALSE	/	FALSE	0	sessionId	1eae0cae-6eba-9305-cc10-8525044a6c50`;

const COOKIE_FILE = path.join(__dirname, 'cookies.txt');

// কুকি ফাইল লেখা (শুধুমাত্র যদি ফাইল না থাকে)
if (!fs.existsSync(COOKIE_FILE)) {
  fs.writeFileSync(COOKIE_FILE, COOKIE_CONTENT, 'utf8');
  console.log('✅ cookies.txt ফাইল তৈরি করা হয়েছে।');
}

// ========== কনফিগারেশন ==========
const DOWNLOAD_DIR = path.join(__dirname, 'downloads');
fs.ensureDirSync(DOWNLOAD_DIR);

// মিডলওয়্যার
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// রেট লিমিট (প্রতি IP থেকে প্রতি 10 মিনিটে 50টি ডাউনলোড)
const limiter = rateLimit({
  windowMs: 10 * 60 * 1000,
  max: 50,
  message: { error: 'Too many requests, please try again later.' }
});
app.use('/download', limiter);

// অ্যাক্টিভ ডাউনলোড ট্র্যাকিং
const activeDownloads = new Map();

// ---------- ইউটিলিটি ফাংশন ----------
function formatFileSize(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

// ডাউনলোড ফাংশন (প্রতিটি রিকোয়েস্টের জন্য আলাদা প্রক্রিয়া, কুকি ব্যবহার করে)
async function startDownload(url, downloadId, options = {}) {
  const {
    quality = 'best',
    isAudioOnly = false,
    embedSubs = false,
    embedThumbnail = false
  } = options;

  const outputTemplate = path.join(DOWNLOAD_DIR, `${downloadId}_%(title)s.%(ext)s`);
  
  // ফরম্যাট নির্বাচন
  let format = 'bestvideo+bestaudio/best';
  if (isAudioOnly) format = 'bestaudio/best';
  else if (quality === '1080p') format = 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=1080][ext=mp4]';
  else if (quality === '720p') format = 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720][ext=mp4]';
  else if (quality === '480p') format = 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480][ext=mp4]';

  const args = [
    '--format', format,
    '--merge-output-format', 'mp4',
    '--output', outputTemplate,
    '--no-playlist',
    '--quiet',
    '--no-warnings',
    '--cookies', COOKIE_FILE   // ← কুকি ফাইল ব্যবহার করা হচ্ছে
  ];
  
  if (isAudioOnly) {
    args.push('--extract-audio', '--audio-format', 'mp3', '--audio-quality', '192K');
  }
  if (embedSubs) {
    args.push('--write-subs', '--write-auto-subs', '--sub-langs', 'en,bn,hi');
  }
  if (embedThumbnail && !isAudioOnly) {
    args.push('--embed-thumbnail');
  }
  args.push(url);

  // স্ট্যাটাস আপডেট ফাংশন
  const updateStatus = (status, progressData = {}) => {
    const current = activeDownloads.get(downloadId) || { status: 'queued', progress: 0 };
    activeDownloads.set(downloadId, {
      ...current,
      status,
      progress: progressData.percent || current.progress,
      downloaded: progressData.downloaded,
      total: progressData.total,
      speed: progressData.speed,
      eta: progressData.eta,
      updatedAt: Date.now(),
      url
    });
  };

  updateStatus('downloading');

  return new Promise((resolve, reject) => {
    const ytProcess = spawn('yt-dlp', args, { env: process.env });
    let stderrBuffer = '';

    ytProcess.stderr.on('data', (data) => {
      const text = data.toString();
      stderrBuffer += text;
      // প্রগ্রেস ডেটা বের করা
      const progressMatch = text.match(/\[download\]\s+(\d+(?:\.\d+)?)%\s+of\s+([\d.]+[KMG]?B)\s+at\s+([\d.]+[KMG]?B\/s)\s+ETA\s+(\d+:\d+)/);
      if (progressMatch) {
        const percent = parseFloat(progressMatch[1]);
        const total = progressMatch[2];
        const speed = progressMatch[3];
        const eta = progressMatch[4];
        updateStatus('downloading', { percent, total, speed, eta });
      }
    });

    ytProcess.on('close', async (code) => {
      if (code === 0) {
        // ডাউনলোড সম্পূর্ণ – ফাইল খোঁজা
        const files = await fs.readdir(DOWNLOAD_DIR);
        const downloadedFile = files.find(f => f.startsWith(downloadId));
        if (downloadedFile) {
          const filePath = path.join(DOWNLOAD_DIR, downloadedFile);
          const stats = await fs.stat(filePath);
          updateStatus('completed', { percent: 100, total: formatFileSize(stats.size) });
          resolve({ filePath, fileName: downloadedFile, size: stats.size });
        } else {
          reject(new Error('Downloaded file not found'));
        }
      } else {
        reject(new Error(`yt-dlp exited with code ${code}\n${stderrBuffer}`));
      }
    });

    ytProcess.on('error', (err) => {
      reject(err);
    });
  });
}

// ========== ওয়েব এন্ডপয়েন্ট ==========

// হোম পেজ (সহজ ফর্ম)
app.get('/', (req, res) => {
  res.send(`
    <!DOCTYPE html>
    <html>
    <head><title>Web Downloader Bot with Cookies</title></head>
    <body>
      <h1>🎬 SonyLIV প্রিমিয়াম ডাউনলোডার</h1>
      <form action="/download" method="post">
        <input type="text" name="url" placeholder="ভিডিও লিংক দিন" style="width:400px" required/>
        <select name="quality">
          <option value="best">Best</option>
          <option value="1080p">1080p</option>
          <option value="720p">720p</option>
          <option value="480p">480p</option>
        </select>
        <button type="submit">ডাউনলোড শুরু করুন</button>
      </form>
      <p>✅ কুকি সংযুক্ত করা হয়েছে – SonyLIV প্রিমিয়াম কন্টেন্ট ডাউনলোড সম্ভব।</p>
      <p>📥 প্রতিটি ইউজার আলাদা কমান্ড দিতে পারবেন, সব ডাউনলোড একসাথে হবে।</p>
    </body>
    </html>
  `);
});

// ডাউনলোড রিকোয়েস্ট
app.post('/download', async (req, res) => {
  const { url, quality = 'best', audioOnly = false, subs = false, thumb = false } = req.body;
  if (!url) return res.status(400).json({ error: 'URL is required' });

  const downloadId = uuidv4();
  const clientIp = req.ip;

  // ব্যাকগ্রাউন্ডে ডাউনলোড শুরু করা (নন-ব্লকিং)
  startDownload(url, downloadId, {
    quality,
    isAudioOnly: audioOnly === 'true' || audioOnly === true,
    embedSubs: subs === 'true',
    embedThumbnail: thumb === 'true'
  }).then(async (result) => {
    // ডাউনলোড সম্পূর্ণ – ফাইল ইউআরএল তৈরি
    const fileUrl = `/files/${downloadId}/${encodeURIComponent(result.fileName)}`;
    console.log(`✅ Download ${downloadId} completed for ${url} from ${clientIp}`);
    // (ঐচ্ছিক) আপনি চাইলে এখানে ওয়েবহুক বা নোটিফিকেশন পাঠাতে পারেন
  }).catch(err => {
    console.error(`❌ Download ${downloadId} failed:`, err.message);
    activeDownloads.set(downloadId, { status: 'failed', error: err.message, url });
  });

  res.json({
    success: true,
    downloadId,
    statusUrl: `/status/${downloadId}`,
    message: 'ডাউনলোড শুরু হয়েছে। স্ট্যাটাস চেক করতে statusUrl ব্যবহার করুন।'
  });
});

// স্ট্যাটাস চেক
app.get('/status/:id', (req, res) => {
  const id = req.params.id;
  const status = activeDownloads.get(id);
  if (!status) return res.json({ status: 'not_found', message: 'No such download or expired.' });
  res.json(status);
});

// ডাউনলোড ফাইল সার্ভ করা
app.get('/files/:id/:filename', async (req, res) => {
  const { id, filename } = req.params;
  const filePath = path.join(DOWNLOAD_DIR, filename);
  if (!filename.startsWith(id) || !await fs.pathExists(filePath)) {
    return res.status(404).send('File not found');
  }
  res.download(filePath, filename);
});

// অ্যাক্টিভ ডাউনলোডের তালিকা (মনিটরিং)
app.get('/active', (req, res) => {
  const active = Array.from(activeDownloads.entries()).map(([id, data]) => ({
    id,
    status: data.status,
    progress: data.progress,
    url: data.url,
    updatedAt: data.updatedAt
  }));
  res.json(active);
});

// সার্ভার চালু
app.listen(PORT, () => {
  console.log(`🚀 Web Downloader Bot is running on port ${PORT}`);
  console.log(`🍪 Cookies file loaded: ${COOKIE_FILE}`);
  console.log(`💾 Download directory: ${DOWNLOAD_DIR}`);
});
